name: Setup aqua
description: Setup aqua for use in GitHub Actions
inputs:
  policy_allow:
    description: "Path to policy file"
    required: false
    default: ""
env:
  AQUA_VERSION: v2.61.0
runs:
  using: composite
  steps:
  - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
    with:
      aqua_version: ${{ env.AQUA_VERSION }}
      policy_allow: ${{ inputs.policy_allow }}
    env:
      GITHUB_TOKEN: ${{ github.token }}
