name: Code scan
on:
  workflow_call:
    inputs:
      issue-id:
        description: "Issue ID to link the scan results to"
        required: false
        type: string
        default: ""
      govulncheck-pre:
        description: "Pre-scan commands for govulncheck"
        required: false
        type: string
        default: ""
  workflow_dispatch:
permissions:
  actions: read
  contents: read
  pull-requests: write
  security-events: write
env:
  GH_TELEMETRY: false
  DO_NOT_TRACK: true
jobs:
  govulncheck:
    name: Govulncheck
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MARKER: "<!-- govulncheck-report -->"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: hsn723/actions/.github/actions/setup-aqua@master
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: stable
      - name: Pre-scan commands
        if: ${{ inputs.govulncheck-pre != '' }}
        run: |
          set -euo pipefail
          ${{ inputs.govulncheck-pre }}
        shell: bash
      - run: |
          FORMAT="sarif"
          if [ "${{ inputs.issue-id }}" != "" ]; then
            FORMAT="text"
            echo "${MARKER}" > govulncheck.report
          fi
          (govulncheck -format "${FORMAT}" ./... || true ) >> govulncheck.report
      - name: Upload SARIF report
        if: ${{ inputs.issue-id == '' }}
        uses: github/codeql-action/upload-sarif@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd # v4.37.7
        with:
          sarif_file: govulncheck.report
      - name: Create or update issue comment
        if: ${{ inputs.issue-id != '' }}
        run: |
          COMMENT_ID=$(gh api repos/${{ github.repository }}/issues/${{inputs.issue-id}}/comments \
            --jq ".[] | select(.body | contains(\"${MARKER}\")) | .id" | head -n 1)
          if [ -n "${COMMENT_ID}" ]; then
            gh api repos/${{ github.repository }}/issues/comments/${COMMENT_ID} \
                -X PATCH \
                -F body=@govulncheck.report
          else
            gh api repos/${{ github.repository }}/issues/${{ inputs.issue-id }}/comments \
                -F body=@govulncheck.report
          fi
