name: Pinact
on:
  workflow_call:
  pull_request:
permissions:
  contents: read
env:
  GH_TELEMETRY: false
  DO_NOT_TRACK: true
jobs:
  check-actions:
    name: Check actions
    runs-on: ubuntu-latest
    steps:
    - uses: hsn723/actions/.github/actions/pinact-action@master
