name: verify
on:
  workflow_call:
    inputs:
      lint-pre:
        description: "Pre-linting commands"
        required: false
        type: string
        default: ""
      lint-post:
        description: "Post-linting commands"
        required: false
        type: string
        default: ""
      test-container:
        description: "Whether to test container images"
        required: false
        type: boolean
        default: true
      additional-dry-run-setup:
        description: "Additional setup commands to run before dry-run (e.g. setting up extra tools)"
        required: false
        type: string
        default: ""
      govulncheck-pre:
        description: "Pre-scan commands for govulncheck"
        required: false
        type: string
        default: ""
permissions:
  contents: read
env:
  GH_TELEMETRY: false
  DO_NOT_TRACK: true
jobs:
  dependency-review:
    name: Dependency review
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          comment-summary-in-pr: true
          allow-dependencies-licenses: |-
            pkg:githubactions/hsn723/actions/.github/actions/pre-commit
            pkg:githubactions/hsn723/actions/.github/actions/setup-aqua
            pkg:githubactions/hsn723/actions/.github/actions/pinact-action
            pkg:githubactions/hsn723/actions/.github/workflows/pinact.yml
            pkg:githubactions/hsn723/actions/.github/workflows/helm-release.yml
            pkg:githubactions/hsn723/actions/.github/workflows/verify.yml
            pkg:githubactions/hsn723/actions/.github/workflows/update-tags.yml
            pkg:githubactions/hsn723/actions/.github/workflows/release.yml
            pkg:githubactions/hsn723/actions/.github/workflows/update-aqua.yml
            pkg:githubactions/hsn723/actions/.github/workflows/create-release-pr.yml
            pkg:githubactions/hsn723/actions/.github/workflows/read-version.yml
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: stable
      - name: Pre-linting commands
        if: ${{ inputs.lint-pre != '' }}
        run: |
          set -euo pipefail
          ${{ inputs.lint-pre }}
        shell: bash
      - uses: hsn723/actions/.github/actions/pre-commit@master
        with:
          extra-args: --all-files
      - name: Post-linting commands
        if: ${{ inputs.lint-post != '' }}
        run: |
          set -euo pipefail
          ${{ inputs.lint-post }}
        shell: bash
  govulncheck:
    name: Govulncheck
    if: ${{ github.event_name == 'pull_request' }}
    uses: hsn723/actions/.github/workflows/code-scan.yml@master
    permissions:
      actions: read
      contents: read
      pull-requests: write
      security-events: write
    secrets: inherit
    with:
      issue-id: ${{ github.event.number }}
      govulncheck-pre: ${{ inputs.govulncheck-pre }}
  check-goreleaser-config:
    name: Check goreleaser.yml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          version: latest
          args: check -f .goreleaser.yml
  pinact:
    name: Pinact
    if: ${{ github.event_name == 'pull_request' }}
    uses: hsn723/actions/.github/workflows/pinact.yml@master
    secrets: inherit
  dry-run:
    name: Dry-run release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: hsn723/actions/.github/actions/setup-aqua@master
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: stable
      - uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
      - name: Setup latest version tag
        run: |
          echo "GORELEASER_CURRENT_TAG=$(git describe --tags --abbrev=0 --match "v*" || echo v0.0.0)" >> $GITHUB_ENV
      - name: Additional dry-run setup
        if: ${{ inputs.additional-dry-run-setup != '' }}
        run: |
          set -euo pipefail
          ${{ inputs.additional-dry-run-setup }}
        shell: bash
      - uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          version: latest
          args: --snapshot --skip=sign,publish --clean
      - name: Test container images
        if: ${{ inputs.test-container }}
        run: |
          REPOSITORY="$(printf '%s' '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')"
          yq '.builds[].goarch[]' .goreleaser.yml | sort -u | \
          xargs -I {} container-structure-test test --image ghcr.io/${REPOSITORY}:${GORELEASER_CURRENT_TAG}-next-{} --platform linux/{} --config cst.yaml
